{
    'name': 'Consignment Management',
    'version': '1.0',
    'summary': 'Manage consignment orders and shipments',
    'author': 'Cuong Nguyen',
    'category': 'Inventory',
    'depends': ['sale', 'stock', 'account', 'custom_sale', 'auto_serial_number', 'custom_product'],
    'data': [
        'data/group_data.xml',
        'data/ir_actions_act_window.xml',
        'views/consignment_sale_order_form_view.xml',
        'views/consignment_sale_order_filter.xml',
        'views/consignment_picking_form_view.xml',
        'views/consignment_invoice_form_view.xml',
        'views/account_move_send_wizard_form.xml',
        'views/sale_view.xml',
        'data/ir_ui_menu.xml',
        'data/ir_rule.xml',
        'data/sequence.xml',
        'views/stock_order_view.xml',
        'reports/custom_sale_order_report.xml',
        'reports/consignment_order_report_non_price.xml',
        'data/decimal_currency_usd.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}