# -*- coding: utf-8 -*-
{
    'name': 'Custom Stock Picking',
    'version': '18.0.1.0',
    'category': 'Inventory',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Cuong Nguyen',
    'depends': [
        'stock',
        'web_grid',
        'web_hierarchy',
        'web_studio',
        'product',
        'custom_sale',
        'custom_product'
    ],
    'data': [
        'views/custom_stock_picking_form_view.xml',
        'data/report_stock_picking_move_barcode.xml',
        'data/report_stock_picking_move.xml',
        'views/product_product_stock_tree.xml',
    ],
    'assets': {
        'web.assets_common': [
            'custom_stock_picking/static/src/fonts/NotoSansKhmer-VariableFont_wdth,wght.ttf',
        ],
    },
    'license': 'OPL-1',
    'installable': True,
    'application': False,
}
