from . import consignment_order
from . import consignment_picking
from . import consignment_invoice
from . import res_partner
from . import sale_order_line
from . import stock_move
from . import consignment_sale_advance_payment_inv
from . import consignment_payment
from . import consignment_journal
from . import consignment_picking_type
from . import picking_label_type_inherit